repos:
    - repo: https://github.com/rtts/djhtml
      rev: v1.5.0
      hooks:
          - id: djhtml
            files: .*/templates/.*\.html$
          - id: djcss
            files: .*/static/.*\.css$
          - id: djjs
            files: .*/static/.*\.js$

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.7.0
      hooks:
          - id: django-upgrade
            args: [--target-version, "4.0"]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
          - id: prettier
            files: \.(lock|json|yaml|yml|md)$|./backend/\.(html)$|./frontend/\.(js|jsx|ts|tsx|css|sass|scss|svelte|html)$
            args:
                [
                    --tab-width,
                    "4",
                    --use-tabs,
                    "false",
                    --bracket-same-line,
                    "false",
                    "--single-quote",
                    "false",
                ]
            additional_dependencies:
                - prettier@2.6.2
                - prettier-plugin-svelte@2.7.0

    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--profile, black]

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.16.0
      hooks:
          - id: eslint
            args: [
                    ./frontend,
                    # --config,
                    # ./frontend/AnimeCore/.eslintrc.cjs,
                    --ignore-pattern,
                    /backend/static/*,
                    --fix,
                ]
            additional_dependencies:
                - eslint@8.16.0
                - eslint-config-prettier@8.5.0
                - eslint-plugin-svelte3@4.0.0
                - "@typescript-eslint/eslint-plugin@5.25.0"
                - "@typescript-eslint/parser@5.25.0"
                - eslint-plugin-simple-import-sort@7.0.0
                - typescript@4.6.4
