repos:
    - repo: https://github.com/rtts/djhtml
      rev: '3.0.6' # replace with the latest tag on GitHub
      hooks:
          - id: djhtml
          - id: djcss
          - id: djjs

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            args: ['--line-length', '92', '--target-version', 'py311']

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.14.1
      hooks:
          - id: django-upgrade
            args: [--target-version, '4.2']

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
          - id: sort-simple-yaml

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.10.1
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: '1.1.0'
      hooks:
          - id: pyproject-fmt

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: 'v0.0.288'
      hooks:
          - id: ruff
            # Respect `exclude` and `extend-exclude` settings.
            args:
                [
                    '--fix',
                    '--respect-gitignore',
                    '--exclude',
                    './tools',

                ]
