repos:
    - repo: https://github.com/rtts/djhtml
      rev: 'v1.5.2' # replace with the latest tag on GitHub
      hooks:
          - id: djhtml
          - id: djcss
          - id: djjs

    - repo: https://github.com/myint/autoflake
      rev: 'v1.4'
      hooks:
          - id: autoflake
            args:
                [
                    '-i',
                    '--remove-all-unused-imports',
                    '--recursive',
                    '--ignore-init-module-imports',
                ]

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.7.0
      hooks:
          - id: django-upgrade
            args: [--target-version, '4.0']

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
          - id: sort-simple-yaml

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            files: \.(lock|json|yaml|yml|md)$|./backend/\.(html)$|./frontend/\.(js|jsx|ts|tsx|css|sass|scss|svelte|html)$
            args:
                [
                    --tab-width,
                    '4',
                    --use-tabs,
                    'false',
                    --bracket-same-line,
                    'false',
                    '--single-quote',
                    'false',
                ]
            additional_dependencies:
                - prettier@2.6.2
                - prettier-plugin-svelte@2.7.0

    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--profile, black, --ca, --cs]

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.21.0
      hooks:
          - id: eslint
            args: [
                    ./frontend,
                    # --config,
                    # ./frontend/AnimeCore/.eslintrc.cjs,
                    --ignore-pattern,
                    /backend/static/*,
                    --fix,
                ]
            additional_dependencies:
                - eslint@8.16.0
                - eslint-config-prettier@8.5.0
                - eslint-plugin-svelte3@4.0.0
                - '@typescript-eslint/eslint-plugin@5.25.0'
                - '@typescript-eslint/parser@5.25.0'
                - eslint-plugin-simple-import-sort@7.0.0
                - eslint-plugin-unused-imports@2.0.0
                - typescript@4.7.4
