name: Seeder

on:
    push:
        branches: ['master']
        paths: ['packages/seeder/**']
    pull_request:
        branches: ['master']
        paths: ['packages/seeder/**']

defaults:
    run:
        working-directory: seeder

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        name: Build on ${{ matrix.os }}
        steps:
            - name: Checkout Seeder
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  cache-dependency-path: seeder/package-lock.json
            - name: Install Dependencies
              run: npm ci
            - name: Run Build
              run: npm run build
