name: tracker

on:
    push:
        branches: ['master']
        paths: ['tracker/**']
    pull_request:
        branches: ['master']
        paths: ['tracker/**']

jobs:
    build-frontend:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        name: Build on ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  cache: 'npm'
                  cache-dependency-path: tracker/frontend/package-lock.json

            - name: Install frontend dependencies
              run: npm i
              working-directory: tracker/frontend

            - name: Build frontend
              run: npm run build
              working-directory: tracker/frontend
